
version: '3.5'

services:
  # app:
  #   build:
  #     context: .
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./app:/app
  #   command: >
  #     sh -c "python3 manage.py migrate &&
  #            python3 manage.py runserver 0.0.0.0:8000"
 
  #   environment:
  #     - DB_HOST=postgres
  #     - DB_NAME=app
  #     - DB_USER=postgres
  #     - DB_PASS=changeme
  #   depends_on:
  #     - postgres

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
